<?php

namespace App\Support;

use Illuminate\Support\Facades\Cache;

/**
 * Central place for the recap cache keys and invalidation.
 *
 * A version token is used instead of cache tags because the application's
 * cache store (Redis) supports tags, but a token works with any driver and
 * lets us invalidate every recap page in a single write when a ticket or
 * channel changes.
 */
class RekapCache
{
    /**
     * Cache key holding the current version token.
     */
    public const VERSION_KEY = 'rekap:version';

    /**
     * Shape of the cached payload. Bump this whenever the payload structure
     * changes so keys generated by older code can never be reused — the
     * version token alone only covers data changes, not code changes.
     */
    public const SCHEMA = 'v2';

    /**
     * How long the generated recap payloads stay cached (seconds).
     */
    public const TTL = 3600;

    /**
     * Resolve the current version token, creating one on first use.
     */
    public static function version(): string
    {
        return (string) Cache::rememberForever(
            self::VERSION_KEY,
            fn (): string => (string) now()->getTimestampMs()
        );
    }

    /**
     * Build a cache key that is tied to the current version token.
     */
    public static function key(string $type, string $period): string
    {
        return sprintf('rekap:%s:%s:%s:%s', self::SCHEMA, $type, $period, self::version());
    }

    /**
     * Rotate the version token so every recap payload is regenerated.
     */
    public static function invalidate(): void
    {
        Cache::forever(self::VERSION_KEY, (string) now()->getTimestampMs());
    }
}
